version: '3.8'
networks:
  network:
    ipam:
      config:
        - subnet: 172.25.0.0/16

services:
  app:
    build:
      dockerfile: Dockerfile
      context: ./firstlaravel
    container_name: laravel_app
    command: sh -c "composer install && /bin/bash /var/www/html/script.sh"
    ports:
      - "5000:8000"
      - "3000:3000"
    volumes:
      - ./firstlaravel:/var/www/html
    links:
      - db
    networks:
      network:
        ipv4_address: 172.25.0.2


  db:
    image: 'mysql'
    container_name: 'mysqldb'
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    ports:
      - '5306:3306'
    command: --sql_mode='STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION'
    environment:
      MYSQL_HOST: 172.25.0.3
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: invoice_manager
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    networks:
      network:
        ipv4_address: 172.25.0.3


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "5080:80"
    depends_on:
      - db
    networks:
      network:
        ipv4_address: 172.25.0.4

volumes:
  dbdata: